/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CropCropSlugRouteImport } from './routes/crop.$cropSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CropCropSlugRoute = CropCropSlugRouteImport.update({
  id: '/crop/$cropSlug',
  path: '/crop/$cropSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/crop/$cropSlug': typeof CropCropSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/crop/$cropSlug': typeof CropCropSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/crop/$cropSlug': typeof CropCropSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/crops' | '/dashboard' | '/login' | '/crop/$cropSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/crops' | '/dashboard' | '/login' | '/crop/$cropSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/crops'
    | '/dashboard'
    | '/login'
    | '/crop/$cropSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CropsRoute: typeof CropsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  CropCropSlugRoute: typeof CropCropSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop/$cropSlug': {
      id: '/crop/$cropSlug'
      path: '/crop/$cropSlug'
      fullPath: '/crop/$cropSlug'
      preLoaderRoute: typeof CropCropSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CropsRoute: CropsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  CropCropSlugRoute: CropCropSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
